# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelMate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TravelMate
  pod 'AFNetworking', '~> 3.0'
  pod 'ActionSheetPicker-3.0', '~> 2.2.0'
  pod 'SDWebImage', '~> 4.1'

  target 'TravelMateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelMateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
